version: '3'
services:
 # Nginx server configuration   
  web:
    image: nginx:latest
    container_name: webserver
    depends_on:
      - db
      - php
    links:
      - db
      - php
    volumes:
      - ./src:/var/www/html
      - ./yii:/var/www/yii
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
 # Php-fpm configuration
  php:
    # image: php:7.4-fpm
    build:
      context: .
      dockerfile: Dockerfile
    image: result/latest
    container_name: php
    links:
      - db
    volumes:
      - ./src:/var/www/html
      - ./php:/usr/local/etc/php/php.ini
      - ./yii:/var/www/yii
 # Mysql configuration
  db:
    image: mysql:8
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        - MYSQL_DATABASE=adrbllDB
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=test
        - MYSQL_PASSWORD=password
    ports:
        - 3308:3306
    volumes:
        - /dbdata:/var/lib/mysql
volumes:
  Dbdata: